### ISSUE TITLE
conda-installed graphviz not working on linux/travis

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/nbsite#16]
I either didn't capture the dependencies properly, or the conda install graphviz that works on my laptop doesn't work on linux/travis. Will need to investigate.

Local build:
<img width="927" alt="screen shot 2017-11-23 at 1 43 00 pm" src="https://user-images.githubusercontent.com/1929/33175646-50646c80-d054-11e7-95c5-b20466b00ea0.png">

Travis build:
<img width="1093" alt="screen shot 2017-11-23 at 1 43 26 pm" src="https://user-images.githubusercontent.com/1929/33175653-55060a46-d054-11e7-8b97-0a3fa93dc2f3.png">

**Comment by ceball** [comment]
Using a miniconda docker container just now, I got this:

<img width="1038" alt="screen shot 2017-12-03 at 12 54 42 am" src="https://user-images.githubusercontent.com/1929/33521247-b8bbaaec-d7c4-11e7-9329-9dd916ea7fa8.png">

Same environment specification (except for unpinned dependencies...). At least it's getting closer to working ;)

**Comment by philippjfr** [comment]
No longer appears to be an issue.
