### ISSUE TITLE
status.pyviz.org has incorrect DNS

### ISSUE THREAD

**Issue by oogali** [pyviz-dev/nbsite#227]
Within the README, there is a reference to https://status.pyviz.org to get the current status of pyviz and pyviz-related components.

The problem is the DNS CNAME currently points to `pyviz-dev.github.io` which does not contain any PyViz or Holoviz content whatsoever.

After looking at other working sites (e.g. `hvplot.pyviz.org` and `nbsite.pyviz.org`), it appears that the **proper** setup should be:
* `status.pyviz.org` DNS CNAME to `webredir.gandi.net`
* Gandi redirection configuration that maps `status.pyviz.org` to `status.holoviz.org`

**Comment by droumis** [comment]
Thanks for catching the issue with the links. Here are the fixes that I see need to be made

-  hvplot.pyviz.org should be https://hvplot.holoviz.org/
-  nbsite.pyviz.org should be https://nbsite.holoviz.org/
-  status.pyviz.org should be https://pyviz.org/tools.html
