### ISSUE TITLE
Remove nbsite.js

### ISSUE THREAD

**Issue by maximlt** [pyviz-dev/nbsite#239]
Most of its content is 5 years old, I don't think it's of any use.

**Comment by philippjfr** [comment]
Agreed, not even quite sure what it's doing.

**Comment by philippjfr** [comment]
Deleted it and haven't seen any change in behavior.

**Comment by philippjfr** [comment]
I do remember what it was for though, it was expanding/collapsing individual classes in the API reference pages but I don't think it has worked since we switched to the pydata-sphinx-theme.
