### ISSUE TITLE
Remove require.js?

### ISSUE THREAD

**Issue by maximlt** [pyviz-dev/nbsite#240]
NBSite is shipping a pretty old version of require.js. I know I've needed require.js to get Plotly plot to be displayed (directly, not via HoloViews) on hvPlot. Except that kind of case, that seems unusual in HoloViz, I'm not sure require.js is of any use now.

**Comment by philippjfr** [comment]
I'm not really sure in what form we are shipping require.js. I don't see it on any of our sites.

**Comment by maximlt** [comment]
You removed the `require.js` file that was in `nbsite/_shared_static`, right?

**Comment by philippjfr** [comment]
Yeah, I found it, and then deleted it :)

**Comment by maximlt** [comment]
Ok thanks.

Actually I remember I had to fiddle with `require.js` in hvPlot's docs to display a plotly plot, rendered directly and not through HoloViews' machinery. This is the comment I left https://github.com/holoviz/hvplot/blob/874e4d9835980b820aaa36802e1449f4ad0ee163/doc/conf.py#L26

And indeed the dev built of hvPlot no longer shows that plot https://pyviz-dev.github.io/hvplot/user_guide/Plotting_Extensions.html

<img width="1023" alt="image" src="https://github.com/pyviz-dev/nbsite/assets/35924738/f56e1992-3927-4739-8fe8-01371baf34dd">

```
Uncaught ReferenceError: require is not defined
    <anonymous> https://pyviz-dev.github.io/hvplot/user_guide/Plotting_Extensions.html:5988
```

But I bet there's another way to render that plot on the site without requiring nbsite to bundle `require.js`.

**Comment by philippjfr** [comment]
Worst case we just use Panel to render the figure.
