### ISSUE TITLE
Expose/document "autolinkable"

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/nbsite#28]
Allows automatic link creation from names in notebook to more detailed docs. E.g. hv links NdLayout in a notebook to the NdLayout reference notebook.

**Comment by jsignell** [comment]
I think this is beyond the scope of nbsite.

**Comment by jbednar** [comment]
I'm a bit confused; as the issue was written, it sounds like `autolinkable` was already part of nbsite, but I don't see it anywhere in the Python nbsite module.  I don't personally think this is an essential feature, but I do think it would be a nice to have someday.
