### ISSUE TITLE
Port work on pyviz.org back here so available generally

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/nbsite#39]
Some workarounds were done for pyviz.org, which now looks a bit more how we'd like nbsites to look in general. Those workarounds should be brought properly into nbsite so all projects can get the benefits.

Including:
  * ...logos...(to be filled in)

**Comment by jsignell** [comment]
I am closing this since I think that sphinx_pyviz_theme captures most of what is being discussed here.
