### ISSUE TITLE
Allow CSS updates with libsass

### ISSUE THREAD

**Issue by jlstevens** [pyviz-dev/nbsite#82]
I'm filing this issue to keep track of some discussion we had regarding nbsite before I forget about it.

The theme we have was originally inherited from bokeh which uses SCSS to build CSS. If you want to update the main colours of the theme, you currently have a very nasty CSS file to work through.

Bokeh currently uses a ruby tool to compile the SCSS to CSS which is not ideal. Some quick investigation suggests that we should be able to do something like:

```
conda install -c conda-forge libsass
```

```
pysassc -I theme/static/scss/base/ -I theme/static/scss/bourbon/ -I theme/static/scss/neat/ -t compressed theme/static/scss/main.scss
```

Where the SCSS files are not currently included by nbsite (but should be).

**Comment by jsignell** [comment]
I think this is no longer as important since I implemented sphinx_pyviz_theme which uses sphinx css templating
