### ISSUE TITLE
Errors running notebooks with nbconvert 5.4? (after pip install nbsite)

### ISSUE THREAD

**Issue by ceball** [pyviz-dev/nbsite#84]
See e.g. https://travis-ci.org/ioam/param/jobs/440195588#L658

nbsite uses nbconvert to execute notebooks. Although I recently tried to update nbsite to work with nbconvert 5.4 (released about a month ago), it seems that I was not actually successful.

nbsite contains some hacks to execute code at notebook startup. We should really revisit this mechanism, because it's a complete hack. nbconvert 5.4 (the first release in over a year) appears to have made various changes to the execute preprocessor, probably breaking our hack:

> Overall the ExecutePreprocessor has been reworked to make it easier to use. Future releases will continue this trend to make this section of the code more inheritable and reusable by others. We encourage you read the source code for this version if you’re interested in the detailed improvements.

(https://nbconvert.readthedocs.io/en/latest/changelog.html)

Default startup code (can be overridden by a project, but probably nobody does that): https://github.com/pyviz/nbsite/blob/master/nbsite/ipystartup.py

Hack to execute it: https://github.com/pyviz/nbsite/blob/master/nbsite/nbbuild.py#L55

Surely there's a better way to achieve that?

Should also verify that the problem in the travis link above is definitely from nbconvert 5.4; most of this post is just speculation.

**Comment by ceball** [comment]
https://github.com/ioam/param/pull/293 indicates that there is some problem with nbsite and nbconvert 5.4, because installing <5.4 fixes the problem.

**Comment by jbednar** [comment]
For now please pin nbconvert here.
